[assembly: System.Reflection.AssemblyProduct("Rox Camera Control")]
[assembly: System.Reflection.AssemblyCompany("AiRoBo Software")]
[assembly: System.Reflection.AssemblyCopyright("©2021 AiRoBo Software")]
[assembly: System.Reflection.AssemblyDescription("Visit us at https://airobo.software.")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]